import { app } from 'electron'
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import { delimiter, join } from 'path'

// Quartz and npm run under Electron's own Node instead of one the user had to install first.
// Electron 43 carries Node 24.18.1, which clears Quartz's `engines.node >= 22` - measured with a
// full build of the test project - so the only thing missing is a way for the twelve `npm`/`npx`
// spawns in this app, and for the lifecycle scripts npm itself starts, to find it.
//
// That way is a directory of three shell scripts at the front of PATH, not a rewrite of every
// spawn site: `sh -c node install.js` in a package's install script has no idea about this app and
// can only be served by a `node` on PATH. Once that exists, every other redirection is redundant -
// buildService, runCommand and the five services above them keep asking for `npx` and get ours.
//
// Why not "host first" the way git is resolved (see gitRuntime, phase 7c): Node has a hard floor
// (>= 22) and a Quartz project ships a `.node-version` pinning v22.16.0, which fnm, nvm, asdf and
// mise all resolve *per directory* - and every spawn here runs with cwd = the project. Host-first
// would therefore hand the build to whatever the user's version manager makes of a file none of us
// wrote. git is the opposite case: no version floor, but the user's config and credential helpers.

export interface EmbeddedRuntime {
  /** Directory prepended to PATH; holds `node`, `npm` and `npx`. */
  binDir: string
  /** The Node version those three provide - Electron's own. */
  nodeVersion: string
  /** Version of the npm that travels with the app, read from its package.json. */
  npmVersion: string | null
}

// Non-null means the shims are written and on PATH. Null means the user chose their own Node
// (Settings), so nothing of ours is in the way and `node` resolves to whatever the machine has.
let runtime: EmbeddedRuntime | null = null

// Both trees sit next to the packaged app (electron-builder `extraResources` flattens them into
// Resources/) and somewhere else entirely in the repo, so each is looked up in both places rather
// than derived from one - the same shape as resolveIconPath() in index.ts.
function packagedOr(packagedName: string, repoPath: string): string {
  const packaged = join(process.resourcesPath, packagedName)
  if (existsSync(packaged)) return packaged
  return join(app.getAppPath(), repoPath)
}

function loaderPath(): string {
  return join(packagedOr('runtime', 'resources/runtime'), 'defaultapp.cjs')
}

// npm is a devDependency, so a production install (--omit=dev) has it only via extraResources.
function npmDir(): string {
  return packagedOr('npm', 'node_modules/npm')
}

/** Quotes a path for a POSIX shell, so a space in "Application Support" cannot split a word. */
function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

function shim(target: string | null): string {
  const electron = shellQuote(process.execPath)
  const loader = shellQuote(loaderPath())
  const script = target ? ` ${shellQuote(target)}` : ''
  return [
    '#!/bin/sh',
    '# Generated by QuartzControl on every start - do not edit, and do not expect it to survive.',
    `ELECTRON_RUN_AS_NODE=1 exec ${electron} -r ${loader}${script} "$@"`,
    ''
  ].join('\n')
}

/**
 * Applies the user's choice of runtime: 'embedded' writes the three shims and puts them at the
 * front of PATH, 'system' takes them back out again. Called at startup and after every save of
 * the setting, so the stored value and the live PATH cannot disagree.
 *
 * The shims are rewritten on every start rather than only when missing: they hold an absolute path
 * to the Electron binary, and inside an AppImage that path lives under a mount point that changes
 * with each launch (/tmp/.mount_…). A shim from yesterday points at nothing.
 *
 * Switching to 'system' only changes what *later* spawns see. A dev server that is already running
 * keeps the environment it was started with - which is why the setting says so.
 */
export function applyRuntimeMode(mode: 'embedded' | 'system'): EmbeddedRuntime | null {
  if (mode === 'system') {
    if (runtime) {
      const gone = runtime.binDir
      process.env.PATH = (process.env.PATH ?? '')
        .split(delimiter)
        .filter((entry) => entry && entry !== gone)
        .join(delimiter)
      runtime = null
    }
    return null
  }
  if (runtime) return runtime

  const binDir = join(app.getPath('userData'), 'runtime', 'bin')
  mkdirSync(binDir, { recursive: true })

  const npm = npmDir()
  const scripts: [string, string | null][] = [
    ['node', null],
    ['npm', join(npm, 'bin/npm-cli.js')],
    ['npx', join(npm, 'bin/npx-cli.js')]
  ]
  for (const [name, target] of scripts) {
    const path = join(binDir, name)
    writeFileSync(path, shim(target), 'utf-8')
    chmodSync(path, 0o755)
  }

  process.env.PATH = [binDir, ...(process.env.PATH ?? '').split(delimiter).filter(Boolean)].join(delimiter)

  let npmVersion: string | null = null
  try {
    npmVersion = JSON.parse(readFileSync(join(npm, 'package.json'), 'utf-8')).version ?? null
  } catch {
    npmVersion = null
  }

  runtime = { binDir, nodeVersion: process.versions.node, npmVersion }
  return runtime
}

/** What was resolved, for the start screen. Null until ensureEmbeddedRuntime() has run. */
export function embeddedRuntime(): EmbeddedRuntime | null {
  return runtime
}
